version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler:2.2.7
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/rspec-test
