version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.6.3-stretch
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
